version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  firefox-node:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  search-module:
    image: watarus62/container-test:demo
    container_name: search-module
    depends_on:
      - firefox-node
      - chrome-node
    environment:
      - MODULE=search-module.xml
      - BROWSER=firefox
      - SELENIUM_HUB=selenium-hub
    volumes:
      - ./logs/search-module:/output

  order-module:
    image: watarus62/container-test:demo
    container_name: order-module
    depends_on:
      - firefox-node
      - chrome-node
    environment:
      - MODULE=order-module.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - ./logs/order-module:/output